
name: 'ecom'
version: '1.0.0'
config-version: 2

profile: 'ecom'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  ecom:
    # Config for all models
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
