channels:
- conda-forge
dependencies:
- python=3.11.14
- pip<=24.0
- pip:
  - mlflow==2.14.1
  - numpy==1.26.4
  - pandas==2.3.3
  - pyarrow==15.0.2
  - scikit-learn==1.8.0
  - scipy==1.16.3
  - xgboost==1.7.6
name: mlflow-env
