version: 2

models:
  - name: fct_sessions
    description: "Sessionized event data"
    columns:
      - name: session_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - relationships:
              to: ref('stg_users')
              field: user_id
  
  - name: mart_funnel
    description: "Funnel analysis aggregated by traffic source"
    columns:
      - name: traffic_source
        tests:
          - unique
          - not_null

  - name: mart_retention
    description: "Weekly cohort retention analysis"
    columns:
      - name: cohort_week
        tests:
          - not_null
      - name: period_number
        tests:
          - not_null

  - name: mart_churn_features
    description: "Feature Training Set for Churn Prediction (One row per user)"
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: is_churned
        description: "1 if recency > 90 days, else 0"
        tests:
          - accepted_values:
              values: [0, 1]

